name: DarkForest
version: ${version}
main: cjs.DF_Plugin.DF_Main
api-version: '1.21'
author: CJS
description: DarkForest 2.0 Plugin

commands:
  df:
    description: DarkForest main command.
    usage: /<command> [subcommand]
    aliases: [darkforest]